### ISSUE TITLE
Pricedifference

### ISSUE THREAD

**Issue by JohanG75** [tibbercom/com.tibber.athom#10]
Hi
There is a diffrent on price in the App on the phone
and the homeyapp 
it only 2 öre but still diffrent

**Comment by toini** [comment]
That should not be possible. We will investigate this. 

Can you tell me the timestamp and value for both?

**Comment by JohanG75** [comment]
![20210225_123452](https://user-images.githubusercontent.com/79634596/109148101-17869e80-7766-11eb-8625-85689687c900.jpg)
this is the latest update
homey was upgraded to 5.0 few days ago

**Comment by toini** [comment]
Unfortunately we had a bug introduced two days ago and it was fixed yesterday. The prices shown in your Homey app are cached which makes it show incorrect numbers. The issue is fixed so tomorrow your prices should show normal again.

**Comment by JohanG75** [comment]
aha
thats why!!!
Tnx for the quick answer 
Keep up the good work!!!
