### ISSUE TITLE
Add conditions and triggers for vacation mode on/off

### ISSUE THREAD

**Issue by jervi** [tibbercom/com.tibber.athom#14]
It would be nice to have the ability to check if a home is in vacation mode or not, and optionally have the ability to turn it on or off.

**Comment by toini** [comment]
We are planning to expose smart heating functionalities (such as vacation mode) through the API. Stay tuned!

**Comment by lovethyresson** [comment]
Closing and adding to backlog.

**Comment by carmaa** [comment]
Any timeline on this?

**Comment by lovethyresson** [comment]
Not right now unfortunately.

Thanks!
Love
