### ISSUE TITLE
Price Level as an AND-argument

### ISSUE THREAD

**Issue by tsuginawa** [tibbercom/com.tibber.athom#15]
Is it possible to get Price Level as an AND-argument, please?

**Comment by tsuginawa** [comment]
Hello? Is anybody from Tibber reading this?

**Comment by toini** [comment]
Hi! Yes, we are reading but we are a bit congested with our backlog at the moment to so we cant promise a time line. What would be the use case you are trying to cover here?

**Comment by tsuginawa** [comment]
The primary use case was to take advantage of Price Level to avoid charging an EV when prices were Expensive or Very Expensive. I've since my first post solved that with some more advanced logic. But Price Level as a condition would be a much simpler and smarter way to use the price level input that is already available from Tibber, without having to compare prices based on average and x hours (which has proven to have some bad side effects when prices change much in a very short time)

**Comment by lovethyresson** [comment]
Closing and adding to backlog.
