### ISSUE TITLE
Outdoor value missing

### ISSUE THREAD

**Issue by badsko** [tibbercom/com.tibber.athom#17]
I'm not receiving any outdoor values. Tried to remove and add back Tibber without any difference. I had a constant value before, which was also wrong.

![6F2EFDE5-111F-4C42-9975-BE2F8538F956](https://user-images.githubusercontent.com/24227209/133427583-5a810e0c-8bbe-45b8-97f6-753e319d6733.png)

Is this working for anyone else?

**Comment by carmaa** [comment]
I also have this issue. Outdoor temp updates very seldom (days in betweeen). Must be a bug? Not much point in having triggers such as “temperature changed” if this is the update rate?

**Comment by jstaro** [comment]
Hi, 
We will remove this in the upcoming version.

**Comment by toini** [comment]
The reason for us removing this is that the outdoor temperature value is not provided by Tibber API, but the original developer chose to fetch it from the Dark sky weather service which has a rate limit for the free account curently in use. We are hitting rate limit now that there are many Tibber apps out there.
