### ISSUE TITLE
Can't find cond_price_among_highest/lowest_today in app (v1.4.13)

### ISSUE THREAD

**Issue by bubblefrog** [tibbercom/com.tibber.athom#18]
**cond_price_among_highest_today** or **cond_price_among_lowest_today** not available as condition in app on homey.

Condition not in app.json, could be some issue with homey compose. Condition is defined in driver.flow.compose.json 

App version: **1.4.13**

**Comment by jstaro** [comment]
This feature was [contributed and merged](https://github.com/tibbercom/com.tibber.athom/pull/9), but due to some structural issues with the code that have since been fixed it has not been officially released yet.

It will be available in the upcoming version. Stay tuned.
