### ISSUE TITLE
Set current price as status indicator

### ISSUE THREAD

**Issue by runely** [tibbercom/com.tibber.athom#19]
I can only set **outdoor** as status indicator. Would like to set **current price** as status indicator as well

**Comment by jstaro** [comment]
This seems to be tied to a convention. Capabilities named `measure_` or `meter_` will work as [device indicators](https://apps.developer.homey.app/the-basics/devices/capabilities#device-indicators-and-custom-capabilities). However, the current price capability does not have a name like that (it was likely added before Athom added this feature), and renaming it would essentially be the same as removing it and adding a new capability, breaking all flows using it.

We would have to consider a breaking change for this, which to me does not seem entirely unreasonable.
