### ISSUE TITLE
Error when changing the Update Interval setting

### ISSUE THREAD

**Issue by TheArcturian** [tibbercom/com.tibber.athom#2]
I get an error when trying to save the "Update Interval" setting under Advanced settings on the device. I try to change the value 30 to 60. It's been like this for a while so it is not related to the recent version 1.1.2.

The error is as follows:

> Invalid setting type! Got undefined but expected string (dropdown) for pulse_currency

Should be easy to correct. In the value Currency (that I dont try to change) the value NOK is selected.

**Comment by toini** [comment]
Thanks for reporting the issue. I will investigate.
