### ISSUE TITLE
Price slow to update in Homey app

### ISSUE THREAD

**Issue by CRidge** [tibbercom/com.tibber.athom#20]
With power prices bouncing up and down like crazy here in Norway at the moment, I've created several flows triggered by price changes in Tibber to try to use power at the right time.

However, I notice the price updates can take hours to actually update. Right now my price in Homey is six hours old, and the price has since been nearly four times that which is represented in Homey.

I have an up to date Homey Pro. What can cause this? I've tried restarting Homey (soft) and the app, with no luck.

I also have a Pulse, which seems to update normally.

**Comment by jstaro** [comment]
Thank you for your report.
There is a new beta/test version (1.5.8) that's in review and currently awaiting approval where this has been fixed.

In the meantime you can find the latest code in the [`dev` branch](https://github.com/tibbercom/com.tibber.athom/tree/dev) which will be merged when the app is released.

**Comment by jstaro** [comment]
We discovered that the Homey release process can be a bit surprising, so the fix for this has now been released as 1.5.10.
