### ISSUE TITLE
v1.5.5 Outside temperature capability removed.

### ISSUE THREAD

**Issue by PeterKawa** [tibbercom/com.tibber.athom#28]
A remark / hint

Quote: 
v1.5.5 - Breaking change: Outdoor temperature capability for Home has been removed. Please use a separate weather app if you need temperature actions for your flows
/Quote

@ Homey cloud and Homey Pro there's an build-in outside temperature tag available.
Based on location based OpenWeather data.

Cloud:
![Screenshot_20211228-183658_Homey](https://user-images.githubusercontent.com/74005072/147592648-aae2cf12-ab31-455c-b4e5-5ac4fbcaa2d9.jpg)

Pro:
![Screenshot_20211228-182904_Homey](https://user-images.githubusercontent.com/74005072/147592645-666085b2-d757-44bf-ab3e-8a59f08d42a5.jpg)

**Comment by lovethyresson** [comment]
That's good input, thanks!
