### ISSUE TITLE
Tibber app v1.4.6 continuously crashes

### ISSUE THREAD

**Issue by aasmundbo** [tibbercom/com.tibber.athom#4]
A minute after the Tibber app was updated to v1.4.6, Homey reported that the app had crashed. 

Trying to restart the Tibber app results in another app crash report in Homey.

Diagnostics report: e9a90d23-d409-4480-8628-52b011205f62

**Comment by toini** [comment]
This issue has now been fixed and release is waiting for review by Athom. A quick fix is to install the latest test version https://homey.app/en-us/app/com.tibber/Tibber/test/

**Comment by aasmundbo** [comment]
Thanks for the quick turnaround! Test version 1.4.7 works well for me 👏🏻

**Comment by Mithrox** [comment]
1.4.7 works great here too. I first installed Homey today, and Tibber was one of my first apps, good thing I found this post 👍
