### ISSUE TITLE
Tibber 1.4.6 crashes a few seconds after starting up

### ISSUE THREAD

**Issue by TheArcturian** [tibbercom/com.tibber.athom#5]
As soon as Tibber version 1.4.6 was automatically installed, it crashed a few seconds. Restarting the app or Homey does not help. Diagnostics should already be received plentiful by you. Please fix the bug. Thanks!

**Comment by TheArcturian** [comment]
Still crashes after upgrading to 1.4.7, but now it crashes when I create a "phase changed" flow and it gets triggered.

**Comment by toini** [comment]
We'll investigate this. To confirm: you are first seeing the currents per phase ok and the crash occurs after triggering the phase changed flow? I tried looking for a crash report from you but did not see one. Could you send it manually and share me the id?

**Comment by toini** [comment]
I noticed a bug in the push notification flow. It might not be related but there's anyhow a new test version https://homey.app/en-us/app/com.tibber/Tibber/test/. Could you install that, try the phase current flow and send diagnostics report and share its id?

**Comment by TheArcturian** [comment]
Yes, I will. Installing now. Getting back to you later.

**Comment by TheArcturian** [comment]
Seems to be working now so that is good. Thanks!

On a sidenote: When creating a flow and using the Pulse Device as trigger card, I can choose between "The power changed" and "Power changed". Seems like a double listing that needs a cleanup.

Also the "Tibber push notification" card doesnt send out the first text line. Only text line 2.

**Comment by toini** [comment]
This is the only trigger with the word power in pulse device configuration:

{
        "id": "power_changed",
        "title": {
          "en": "Power changed"
        },
        "tokens": [
          {
            "name": "power",
            "type": "number",
            "title": {
              "en": "Power"
            }
          }
        ],
        "args": [
          {
            "type": "device",
            "name": "device",
            "filter": "driver_id=pulse"
          }
        ]
      },


Could you try to remove and re-add the device so we can see if it gets cleaned up?

**Comment by TheArcturian** [comment]
I removed the Pulse device after installing 1.4.7 and had to update a bunch of flows so I'd rather not do that again with 1.4.8. Here is a screenshot of the list, however it is just a minor troublefree problem:

![Skjermbilde](https://user-images.githubusercontent.com/16746633/101393099-d5686200-38c6-11eb-8f96-1e72a0543479.JPG)

After testing a while today, it seems like the flow card "Current phase 3 changed" doesn't work. It never gets triggered even though I see in the Tibber app that it should. It does work when I click Test strangely enough. The duplicate flow with the card "Current phase 1 changed" works perfectly.

**Comment by TheArcturian** [comment]
Here is two screenshot of the 2 flows for phase 1 and 3:

![Skjermbilde3](https://user-images.githubusercontent.com/16746633/101393665-bb7b4f00-38c7-11eb-9d78-0667b1c1bb8e.JPG)
![Skjermbilde2](https://user-images.githubusercontent.com/16746633/101393671-bc13e580-38c7-11eb-90ad-db87781c1402.JPG)

In the Tibber app, the measurement of phase 1 is usually around 28. For phase 3 it is around 23. I set the trigger to 9 just to force it to trigger. Here you can see the current values in the web based flow tool:

![Skjermbilde4](https://user-images.githubusercontent.com/16746633/101394011-380e2d80-38c8-11eb-814b-8734fcc6b6e4.JPG)

I also have tested to set the trigger value from 9 to 25 and turn on an oven to make it cross the threshold, but it still doesnt trigger and send the messages. Only when I press Test and set the value higher than the when clause.

**Comment by lovetibber** [comment]
I've reproduced the same error here. @toini, let's look at this when you've got a chance.

**Comment by toini** [comment]
@TheArcturian the issue with "Tibber push notification" card not sending out first text line should now be fixed. Could you try it out?

We are still investigating the trigger issue for the currents.

**Comment by TheArcturian** [comment]
Ok, I'll let you know tomorrow.

**Comment by TheArcturian** [comment]
Moving away from Athom Homey to Home Assistant. Need a much better and responsive solution as a base. Hope to see the these triggers in the Home Assistant integration as well. :-)

**Comment by lovetibber** [comment]
Do we support these already for HA @Danielhiversen ?

**Comment by Danielhiversen** [comment]
These Pulse data are available for automations in HA:

```
power
powerProduction
accumulatedProduction
accumulatedConsumption
accumulatedCost
currency
minPower
averagePower
maxPower
voltagePhase1
voltagePhase2
voltagePhase3
currentL1
currentL2
currentL3
lastMeterConsumption
lastMeterProduction
signalStrength
```

**Comment by TheArcturian** [comment]
Brilliant! :-)

**Comment by toini** [comment]
There's a new test version that solves the issue with L2 / L3 not getting triggered. You can install it here: https://homey.app/en-us/app/com.tibber/Tibber/test/

**Comment by TheArcturian** [comment]
Phase 3 now triggers as expected.
