### ISSUE TITLE
Show day ahead price

### ISSUE THREAD

**Issue by Zeppen** [tibbercom/com.tibber.athom#6]
Suggestion/idea
Would be slick to get the day ahead prices once a day or when called upon.

**Comment by toini** [comment]
Thanks for the suggestion! Where would like to have the day ahead prices put in? We currently populate the insights but it does not support storing them in future.

**Comment by Zeppen** [comment]
Dunno how or where to put it but would be nice to get the price hour by hour when called upon, if graphs not possible via insights then text format would do I guess. 
Same function would be nice to have in the Tibber app too..

**Comment by toini** [comment]
You can see prices hour by hour in text format when you use your credentials to log into the site at https://developer.tibber.com/explorer and then select and run the query "Current energy price". Will that be of any help? 

Note that very high/low prices are notified in the app with push messages which we think provides a nice user experience.

**Comment by lovetibber** [comment]
Hey,

Typically day ahead prices are available from Nordpool around 12 the day before so we could expose them. Could you help explain the intended use case a bit better? Are you looking for triggers, ie "Price tomorrow is above/below x" etc?

**Comment by toini** [comment]
> Same function would be nice to have in the Tibber app too..

Price graphs can be viewed in the app:

![image](https://user-images.githubusercontent.com/7605167/101530274-5c3a3f00-399a-11eb-9a17-28323f454e98.png)

**Comment by Zeppen** [comment]
my bad about the app and graphs.



> You can see prices hour by hour in text format when you use your credentials to log into the site at https://developer.tibber.com/explorer and then select and run the query "Current energy price". Will that be of any help?
> 
> Note that very high/low prices are notified in the app with push messages which we think provides a nice user experience.

yup, that would do it I guess. 
Im looking for the feature of trigging the EV charger (Zappi v2) to use the cheapest hours for charging (combined with solar panels if available and sun is shining)
the thing about the Zappi charger is that there is a Esense function that allows to power charge / economy charge the EV.

I might be on thin ice here but if esense is activated via a power socket (ie sonoff/tasmota / z-wave plug) then the different charging states can be activated (esense function)

Id then steer the power socket depending on the hours with the lowest price 

Eeasee charger is a good one but since one can charge via solar panels using the Zappi charger I prefer that one over Easee.



there is a pretty good documented API of the zappi charger over here.
[https://github.com/twonk/MyEnergi-App-Api](url)

and the wiki of the Zappi charger incl the esense function and so on here [https://myenergi.com/wiki/zappi-v2-wiki/installation-3/#eSenseInput](url)


I might be throwing a bunch of stupid ideas here but would be very nice to see you support more EV chargers than Easee :)

**Comment by lovetibber** [comment]
Hey Zeppen,

I hear you. The primary reason we haven't expanded to multiple charge stations is that getting the logic to work correctly is pretty hard work, and there's also often dependencies on how cars react to different charge settings etc.

We may very well look at adding additional ones down the line.

But should I take it that you are ok with what's available today then? We already have a trigger for "Current price is [x] % below average for the next [y] hours". I'd assume the challenge here is that may not work across 22-06 for example if we don't expose tomorrows prices there, but I'd need @toini to comment if we can today, or if it's a simple fix.

**Comment by Zeppen** [comment]
Thnx, I totally get it about the chargers 😊
I did a ad hoc by using a homey flow plus  "Current price is [x] % below average for the next [y] hours" and together with ä a smartplug connected to the Zappi chargers esense input I can now use the plunge pricing 😊

**Comment by Zeppen** [comment]
All sorted 👍

**Comment by lovetibber** [comment]
Happy you're happy! :)
