### ISSUE TITLE
PriceLevel

### ISSUE THREAD

**Issue by torke1** [tibbercom/com.tibber.athom#7]
Hi,
I really miss the PriceLevel attribute from when I ran Home Assistant. I suppose it would be fairly easy to add as a condition. Can we please have that soon? Pretty please? With sugar on top? :)
Best /Daniel

**Comment by toini** [comment]
Here's a new test version of the Homey Tibber app that has support for showing price level. Would you try it and tell us how it works? You'll need to re-add the home.

https://homey.app/en-us/app/com.tibber/Tibber/test/

**Comment by torke1** [comment]
Wonderful! I've made some test flows for this. I'll get back when I've ran them.a few days. Thanks!

**Comment by torke1** [comment]
Now, I've tried it out for a few days and it seems stable. Took a while to understand how to create a flow using the attribute, but once I got the hang of it, it's working perfectly.

**Comment by toini** [comment]
Nice! We'll publish a new release soon.
