### ISSUE TITLE
Most expensive port sending wrong message

### ISSUE THREAD

**Issue by Dodraugen** [tibbercom/com.tibber.athom#8]
I have two flows.one that turn off devices at VERY EXPENSIVE and ont that turns them on at EXPENSIVE and NORMAL. The problem is that at the most expensive part of the day, the devices turn on. But when I check the tibber api in homey at says it's at very expensive. This only happens at the peak price.

**Comment by lovetibber** [comment]
Hi @Dodraugen, can you share screenshots of your flow settings?

**Comment by Dodraugen** [comment]
![IMG_0920](https://user-images.githubusercontent.com/78906305/107648838-13925100-6c7d-11eb-9da8-d86e9505ad76.PNG)
![IMG_0921](https://user-images.githubusercontent.com/78906305/107648849-17be6e80-6c7d-11eb-8998-2b4711b96258.PNG)
![IMG_0922](https://user-images.githubusercontent.com/78906305/107648852-18ef9b80-6c7d-11eb-9f0d-572f97662892.PNG)
![IMG_0923](https://user-images.githubusercontent.com/78906305/107648854-19883200-6c7d-11eb-835c-832de24fb15a.PNG)
![IMG_0924](https://user-images.githubusercontent.com/78906305/107648855-1a20c880-6c7d-11eb-98eb-7ef4fbf28dab.PNG)
![IMG_0925](https://user-images.githubusercontent.com/78906305/107648856-1ab95f00-6c7d-11eb-9081-d9b77d7c84d5.PNG)

Here you go.

**Comment by lovetibber** [comment]
Hey, thanks!

I think an issue here may be that you use "contains" EXPENSIVE which would make it trigger on priceLevel being both EXPENSIVE and VERY_EXPENSIVE.

Can you try using "is exactly" instead and see if that works?
